image: registry.gitlab.com/ccleberg/cleberg-net:latest

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Environment is ready. Running build..."
    - ENV=prod uv run build.py <<< "r"
  artifacts:
    paths:
      - .build/

deploy-job:
  stage: deploy
  environment: production
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'    
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - |
      echo "Host homelab-remote
          HostName $SERVER_IP
          User $SERVER_USER
          Port 2169" > ~/.ssh/config
  script:
    - echo "Deploying via Python script..."
    - ENV=prod uv run build.py <<< "r"
