image: registry.gitlab.com/ccleberg/cleberg-net:latest

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Environment is ready. Running build..."
    - ENV=prod uv run build.py <<< "r"
  artifacts:
    paths:
      - .build/

deploy-job:
  stage: deploy
  script:
    - mkdir -p $HOME/.ssh
    - chmod 700 $HOME/.ssh
    - ssh-keyscan -p 2169 $SERVER_IP >> $HOME/.ssh/known_hosts
    - |
      echo "Host homelab-remote
          HostName $SERVER_IP
          User $SERVER_USER
          Port 2169" > $HOME/.ssh/config
    - chmod 600 $HOME/.ssh/config
    - echo "Deploying via Python script..."
    - ENV=prod uv run build.py <<< "r"
