name: Build and Deploy

on:
  push:
    branches:
      - '**'
#    branches: [ "main" ]

jobs:
  build-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ccleberg/cleberg.net:github-actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build
        run: |
          echo "Environment is ready. Running build..."
          echo "r" | ENV=prod uv run build.py

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ github.workspace }}/.build/
          include-hidden-files: true

  deploy-job:
    runs-on: ubuntu-latest
    needs: build-job
    environment: production
    container:
      image: ghcr.io/ccleberg/cleberg.net:github-actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ${{ github.workspace }}/.build/

      - name: Setup SSH and Deploy
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY: "true"
          ENV: "prod"
        run: |
          mkdir -p $HOME/.ssh

          cat <<EOF > $HOME/.ssh/config
          Host homelab-remote
          HostName $SERVER_IP
          User $SERVER_USER
          Port 2169
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          EOF
          
          chmod 600 $HOME/.ssh/config
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          
          # DEBUG
          echo "Checking SSH Config:"
          cat $HOME/.ssh/config
          # END DEBUG
          
          echo "Deploying via Python script..."
          uv run build.py
